spring.application.name=logos-srv

spring.datasource.url=${LOGOS_DB_URL:jdbc:postgresql://localhost:15432/logos}
spring.datasource.username=${LOGOS_DB_USERNAME:postgres}
spring.datasource.password=${LOGOS_DB_PASSWORD:postgres}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none

# JWT Configuration
application.security.jwt.secret-key=${LOGOS_JWT_SECRET}
# Tempo de expiração do token em milissegundos (24 horas)
application.security.jwt.expiration=86400000

# Springdoc (Swagger UI) Configuration
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# Enable Spring Security Debug Logging
logging.level.org.springframework.security=DEBUG
