spring.application.name=logos-srv

spring.datasource.url=jdbc:postgresql://localhost:5432/logos
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none

# JWT Configuration
application.security.jwt.secret-key=NzE0YzYxNzA0MzY0NjM1ODU3NzA3NTM4NzQzMDM0Nzg0Zjc3MzU0NjYxMzQzNTY0Mzc0MTM0NTk2YzM5MzQ2MzY1NzY=
# Tempo de expiração do token em milissegundos (24 horas)
application.security.jwt.expiration=86400000

# Springdoc (Swagger UI) Configuration
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# Enable Spring Security Debug Logging
logging.level.org.springframework.security=DEBUG
